"""empty message

Revision ID: e60f4cfefed8
Revises: 7709655c9185
Create Date: 2021-02-08 16:08:46.571014

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'e60f4cfefed8'
down_revision = '7709655c9185'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('t_user', sa.Column('name', sa.String(length=20), nullable=True))
    op.drop_index('username', table_name='t_user')
    op.drop_column('t_user', 'username')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('t_user', sa.Column('username', mysql.VARCHAR(length=20), nullable=True))
    op.create_index('username', 't_user', ['username'], unique=True)
    op.drop_column('t_user', 'name')
    # ### end Alembic commands ###
